---

- name: Install certmonger packages
  yum:
    name: '{{ item }}'
    state: 'latest'
  with_items: [ 'dbus', 'certmonger', 'nss-tools', 'pynag' ]

# ----------------------------------
#   NSS Certificates (IPA default)
# ----------------------------------

- name: Create NSS certificate directory
  file:
    path: '{{ freeipa_client_nss_path }}'
    owner: 'root'
    group: 'root'
    mode: '755'
    state: 'directory'

- name: Create NSS certificate database
  command: certutil -N -d '{{ freeipa_client_nss_path }}' --empty-password
           creates='{{ freeipa_client_nss_path }}/cert8.db'
  notify: [ 'Restart certmonger' ]

- name: Check IPA CA certificate in NSS database
  shell: certutil -L -n 'IPA CA' -d '{{ freeipa_client_nss_path }}' || true
  register: freeipa_register_cacrt
  changed_when: False
  check_mode: no

- name: Add IPA CA certificate to NSS database
  command: certutil -A -d '{{ freeipa_client_nss_path }}' -n 'IPA CA' -t CT,C,C -a -i /etc/ipa/ca.crt
  when: "freeipa_register_cacrt.stderr.startswith('certutil: Could not find cert')"
  notify: [ 'Restart certmonger' ]

# --------------------
#   PEM Certificates
# --------------------

- name: Create X509/PEM certificates location
  file:
    path: '{{ freeipa_client_x509_base_path }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: directory

- name: Create PEM certificate directory
  file:
    path: '{{ freeipa_client_pem_cert_path }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: directory

- name: Create PEM key directory
  file:
    path: '{{ freeipa_client_pem_key_path }}'
    owner: 'root'
    group: '{{ freeipa_client_cert_key_group }}'
    mode: '0750'
    state: directory

- name: Request SSL host certificate
  command: ipa-getcert request \
    -r -w
    -k '{{ freeipa_client_pem_key_path }}/{{ ansible_fqdn }}.key' \
    -f '{{ freeipa_client_pem_cert_path }}/{{ ansible_fqdn }}.crt' \
    -g '{{ freeipa_client_cert_key_size }}' -K 'host/{{ ansible_fqdn }}' \
    -N 'CN={{ ansible_fqdn }},O={{ ipaserver_realm }}' \
    -D '{{ inventory_hostname }}' \
    -U id-kp-serverAuth
  args:
    creates: '{{ freeipa_client_pem_cert_path }}/{{ ansible_fqdn }}.crt'

- name: Set PEM certificate permissions
  file:
    path: '{{ freeipa_client_pem_cert_path }}/{{ ansible_fqdn }}.crt'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Set PEM private key permissions
  file:
    path: '{{ freeipa_client_pem_key_path }}/{{ ansible_fqdn }}.key'
    owner: 'root'
    group: '{{ freeipa_client_cert_key_group }}'
    mode: '0640'

- name: Add IPA CA certificate to global CA certificates
  copy:
    remote_src: true
    src: /etc/ipa/ca.crt
    dest: '/etc/ssl/certs/{{ ipaserver_domain.split(".")[0] | title }}_CA_Root.pem'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: freeipa_client_register_pem_ca_trust
  when: freeipa_client_pem_ca_trust is defined and freeipa_client_pem_ca_trust

- name: Compute IPA CA certificate hash
  command: openssl x509 -hash -noout -in '{{ freeipa_client_register_pem_ca_trust.dest }}'
  register: freeipa_client_register_pem_ca_hash
  when: freeipa_client_register_pem_ca_trust.changed

- name: Create IPA CA certificate hash link
  shell: ln -s `basename '{{ freeipa_client_register_pem_ca_trust.dest }}'` '{{ freeipa_client_register_pem_ca_hash.stdout }}.0'
  args:
    chdir: '/etc/ssl/certs'
    creates: '{{ freeipa_client_register_pem_ca_hash.stdout }}.0'
  when: freeipa_client_register_pem_ca_trust.changed

- name: copy check_certmonger
  copy:
    src: check_certmonger
    dest: /usr/lib64/nagios/plugins/check_certmonger
    owner: root
    group: root
    mode: 0755
  tags:
    - monitoring

- name: copy nrpe check definition
  template:
    src: check_certmonger.cfg.j2
    dest: /etc/nrpe.d/check_certmonger.cfg
    owner: nrpe
    group: nrpe
    mode: 0644
  notify: restart nrpe
  tags:
    - monitoring

- name: Allow nrpe to sudo ipa get-cert
  template:
    src: 50-nrpe-check-certmonger.j2
    dest: /etc/sudoers.d/50-nrpe-check-certmonger
    owner: root
    group: root
    mode: 0640
  tags:
    - monitoring


