---
# tasks file for freeipa-client

- name: Check that ipa server is available
  uri:
    url: 'https://{{ ipaserver_master }}'
    validate_certs: False
  ignore_errors: true
  register: ipa_status
  check_mode: no
  tags:
    - always

- name: Gather OS Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
        - default.yml
      paths:
        - "{{ role_path }}/vars"

- name: Install IPA Client Packages
  yum:
    name: "{{ ipaclient_packages }}"
    state: present
  become: True
  tags:
    - install

- name: Run the IPA Client uninstaller, when ipaclient_reconfigure=True
  shell: "{{ ipaclient_base_command }} --uninstall"
  when: ipaclient_reconfigure
  become: True
  tags:
    - uninstall

- name: Run the IPA Client installer
  shell: >
    {{ ipaclient_base_command }}
    --force-join
    --realm {{ ipaserver_realm }}
    --domain {{ ipaserver_domain }}
    --principal {{ ipaserver_admin_username }}@{{ ipaserver_realm }}
    --password '{{ ipaserver_admin_password }}'
    --hostname={{ inventory_hostname }}
    --enable-dns-updates
    {% for host in groups['ipaservers'] %}
    --ntp-server={{ hostvars[host]['ansible_host'] }}
    {% endfor %}
    {{ '--mkhomedir' if ipaclient_mkhomedir | default(True) else '' }}
    {{ '--ssh-trust-dns' if ipaclient_ssh_trust_dns | default(False) else '' }}
    {{ '--force-ntpd' if ipaclient_setup_ntp | default(False) else '--no-ntp' }}
    {{ '' if ipaclient_configure_ssh | default(True) else '--no-ssh' }}
    {{ '' if ipaclient_configure_sshd | default(True) else '--no-sshd' }}
  args:
    creates: /etc/ipa/default.conf  #already configured, set ipaclient_reconfigure True
  register: ipaclientsetup
  become: True
  when: ipa_status is defined and ipa_status.status == 200
  tags:
    - install

- name: Add IPA CA cert to systemwide store
  copy:
    src: /etc/ipa/ca.crt
    dest: /etc/pki/ca-trust/source/anchors/ipa-ca.pem
  notify: update ca certs
  tags:
    - config
    - ssl

- name: Create an IPA host group
  ipa_hostgroup:
    name: '{{ ipa_hostgroup }}'
    description: '{{ host_description | default(omit) }}'
    host: '{{ groups[ipa_hostgroup] }}'
    state: present
    ipa_host: '{{ ipaserver_master }}'
    ipa_user: admin
    ipa_pass: '{{ ipaserver_admin_password }}'
    validate_certs: False
  when: ipa_hostgroup is defined and ipa_status is defined and ipa_status.status == 200
  run_once: true
  tags:
    - config

- name: Register host with IPA server
  ipa_host:
    name: '{{ inventory_hostname }}'
    description: '{{ host_description | default("") }}'
    ip_address: '{{ ansible_host }}'
    ns_host_location: '{{ ipa_location }}'
    ns_os_version: '{{ ansible_distribution }} {{ ansible_distribution_major_version }}'
    ns_hardware_platform: '{{ ansible_system_vendor }}'
    state: present
    ipa_host: '{{ ipaserver_master }}'
    ipa_user: admin
    ipa_pass: '{{ ipaserver_admin_password }}'
    validate_certs: False
  when: ipa_status is defined and ipa_status.status == 200
  tags:
    - config
